export let users = [
  { id: 1, name: "Eshmat1" },
  { id: 2, name: "Eshmat2" },
  { id: 3, name: "Eshmat3" },
  { id: 4, name: "Eshmat4" },
  { id: 5, name: "Eshmat5" },
  { id: 6, name: "Eshmat6" },
  { id: 1, name: "Eshmat1" },
  { id: 2, name: "Eshmat2" },
  { id: 3, name: "Eshmat3" },
  { id: 4, name: "Eshmat4" },
  { id: 5, name: "Eshmat5" },
  { id: 6, name: "Eshmat6" },
  { id: 1, name: "Eshmat1" },
  { id: 2, name: "Eshmat2" },
  { id: 3, name: "Eshmat3" },
  { id: 4, name: "Eshmat4" },
  { id: 5, name: "Eshmat5" },
  { id: 6, name: "Eshmat6" },
  { id: 1, name: "Eshmat1" },
  { id: 2, name: "Eshmat2" },
  { id: 3, name: "Eshmat3" },
  { id: 4, name: "Eshmat4" },
  { id: 5, name: "Eshmat5" },
  { id: 6, name: "Eshmat6" },
  { id: 1, name: "Eshmat1" },
  { id: 2, name: "Eshmat2" },
  { id: 3, name: "Eshmat3" },
  { id: 4, name: "Eshmat4" },
  { id: 5, name: "Eshmat5" },
  { id: 6, name: "Eshmat6" },
];

export const list = [1, 2, 3, 45];
